
server:
  port: 8084

eureka:
  instance:
    hostname: localhost
    port: 9000
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    server:
      wait-time-in-ms-when-sync-empty: 3000


spring:
  jpa:
    database: financeira
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/financeira
    username: financeira
    password: 123456
    driverClassName: org.hibernate.dialect.PostgreSQLDialect
