
spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: cliente
          uri: lb://CLIENTE
          predicates:
            - Path=/clientes/**
        - id: emprestimo
          uri: lb://EMPRESTIMO
          predicates:
            - Path=/emprestimos/**

  config:
    import: "optional:configserver:"

#server:
#  port: 8083
#  servlet:
#    context-path: /gateway/

eureka:
  instance:
    hostname: localhost
    port: 9000
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    server:
      wait-time-in-ms-when-sync-empty: 3000

